#!/bin/bash

# Set Zed as default application
duti -s dev.zed.Zed .css all
duti -s dev.zed.Zed .erb all
duti -s dev.zed.Zed .go all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .rb all
duti -s dev.zed.Zed .ru all
duti -s dev.zed.Zed .sh all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .xml all

# Set VLC as default application
duti -s org.videolan.vlc .avi all
duti -s org.videolan.vlc .mkv all
duti -s org.videolan.vlc .mp4 all
duti -s org.videolan.vlc .webm all

# Disable Spotlight Shortcut
echo "Disabling Spotlight Shortcut"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist \
  -c "Delete :AppleSymbolicHotKeys:64" \
  -c "Add :AppleSymbolicHotKeys:64:enabled bool false" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters array" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 65535" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 49" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 1048576" \
  -c "Add :AppleSymbolicHotKeys:64:type string standard"
