#!/bin/bash

# Set Keka as default application
duti -s com.aone.keka .7z all
duti -s com.aone.keka .aar all
duti -s com.aone.keka .ace all
duti -s com.aone.keka .br all
duti -s com.aone.keka .bz all
duti -s com.aone.keka .bz2 all
duti -s com.aone.keka .bzip all
duti -s com.aone.keka .bzip2 all
duti -s com.aone.keka .gz all
duti -s com.aone.keka .gzip all
duti -s com.aone.keka .lrz all
duti -s com.aone.keka .lz all
duti -s com.aone.keka .rar all
duti -s com.aone.keka .tar all
duti -s com.aone.keka .wim all
duti -s com.aone.keka .xz all
duti -s com.aone.keka .zip all
duti -s com.aone.keka .zst all

# Set IINA as default application
duti -s com.colliderli.iina .avi all
duti -s com.colliderli.iina .mkv all
duti -s com.colliderli.iina .mov all
duti -s com.colliderli.iina .mp3 all
duti -s com.colliderli.iina .mp4 all
duti -s com.colliderli.iina .webm all

# Set Zed as default application
duti -s dev.zed.Zed .css all
duti -s dev.zed.Zed .erb all
duti -s dev.zed.Zed .go all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .rb all
duti -s dev.zed.Zed .ru all
duti -s dev.zed.Zed .sh all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .xml all

# Disable Spotlight Shortcut
echo "Disabling Spotlight Shortcut"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist \
  -c "Delete :AppleSymbolicHotKeys:64" \
  -c "Add :AppleSymbolicHotKeys:64:enabled bool false" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters array" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 65535" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 49" \
  -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 1048576" \
  -c "Add :AppleSymbolicHotKeys:64:type string standard"

# Speed up animations
echo "Speed up animations"
defaults write com.apple.dock expose-animation-duration -float 0.01
defaults write NSGlobalDomain NSWindowResizeTime -float 0.01
defaults write com.apple.dock autohide-time-modifier -float 0.01
killall Dock
